### ISSUE TITLE
Ошибка при первом открытии модуля в Розница, редакция 2.2 (2.2.12.30)

### ISSUE THREAD

**Issue by pr12yad** [legendcity/legendcity-1c#13]
При первой попытки открытия настройки модуля выдается ошибка
Значение не является значением объектного типа (ТаблицаИдентификаторТерминала)
![Безымянный](https://user-images.githubusercontent.com/95919056/152195153-f9f448bc-fae2-471e-93c8-d66a029ea9fa.png)

**Comment by legendcity** [comment]
https://github.com/legendcity/legendcity-1c/commit/0bca1ae91dd28b264c0ad86558a38102bbecb9f3
